### PR TITLE
[Improvement] Add ListUniCoursesCommand into DG

### LINKED ISSUE #108: Implement DG for ListUniCoursesCommand
To implement developer guide for ListUniCourseCommand

### PR DESCRIPTION
**Pull request by Chiang-HuiXin**
Fixes #108 
 
- Add details of ListUniCoursesCommand into DG.
- Add sequence diagram for ListUniCoursesCommand

### CODE REVIEW

**Review by louisjoety — COMMENTED** [review]
I think because of #120, may need to adjust the diagram

**Review by hzxnancy — COMMENTED** [review]
The UML diagram did not reflect the for loop and opt in the findUniversityName command. Otherwise, LGTM!

**Comment by Chiang-HuiXin** [comment]
- Updated the sequence diagram, please take a look
- Modify DG because of #120

**Review by chewycj — APPROVED** [review]
Looks ready for review in tomorrow's tutorial!! 👍

**Pull request merged**
