### PR TITLE
[Improvement] Update Developer Guide with AddCoursesCommand

### LINKED ISSUE #111: Implement Developer Guide for AddCoursesCommand

### PR DESCRIPTION
**Pull request by hzxnancy**
Fixes #111 

1) Update the Developer Guide with an overview of the feature and how it is implemented.
2) Create a UML diagram of AddCoursesCommands and upload it into the Developer Guide.

### CODE REVIEW

**Review by wahkia — COMMENTED** [review]
Nice and detailed diagram.  We might not need to show all the exception handling. I observed that the activation bars for `:addCourseCommand` and `:CourseValidator` are not closed. otherwise LGTM!

**Review by louisjoety — COMMENTED** [review]
I think because of #120, may need to adjust the diagram

**Comment by hzxnancy** [comment]
Thanks for the comments, I have made the edits!

**Review by chewycj — APPROVED** [review]
LGTM!! I think it is ready for review for tomorrow's tutorial 🚀

**Pull request merged**
